---
name: Benjamin    
surname: Marmont
position: "Economist"
phone: +64 21 0269 2180
email: "BLMarmont@gmail.com"
github: BenMarmont
linkedin: Ben-Marmont
www: researchgate.net/profile/Ben-Marmont
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
```

# Objective

Following the completion of my Master’s in Management (Economics) at the University of Waikato, I have honed my expertise as an Economist at DairyNZ, gaining valuable insights into Agricultural Economics, the Dairy sector, and related primary industries. My goal is to leverage and expand this expertise via a PhD, continuing to apply and enhance the skills and knowledge I have developed.

# Experience

## Economist

**DairyNZ, 2023 - Present** \newline After completing my Masters at DairyNZ I transitioned into a role in their Economics team, where I was part of several pieces of work often spanning longer term research projects and shorter term commentary:

-   Developing and deploying farm-level economic forecasts publicly available on the [**DairyNZ Econ Tracker**](https://connect.dairynz.co.nz/EconTracker/)
-   Redeveloped code for two chapters of [**Dairy Statistics**](https://connect.dairynz.co.nz/2023-24_Dairy_Statistics/) after the publication was transitioned from LIC to DairyNZ
-   Developed sector-wide, farm-level modelling and associated cost-benefit analysis including iterative feedback from collaborators for a business case
-   Lectured R for Data Science at the University of Waikato and tutored an additional two iterations of the course
-   Published two papers from my Masters research [[**1**](https://nzgajournal.org.nz/index.php/JoNZG/article/view/3655), [**2**](https://www.sciencedirect.com/science/article/pii/S2772375524001540?via%3Dihub)], with two more since [[**3**](https://www.researchgate.net/publication/388173097_Enabling_data_science_at_DairyNZ_with_Modern_Science_Workflows), [**4**](https://www.nzgajournal.org.nz/index.php/JoNZG/article/view/3703)]
-   Delivered presentations to discussion groups and curiosity session, with excellent feedback

## Economic Analyst

**Urban Economics, 2021** \newline

I worked a term contract at this consultancy, where I developed my analytical skills in a property economics application including extensive work on a gravity model for retirement villages demand in Auckland

# Education

## Master of Management (Economics, First Class Honours)

**University of Waikato, 2021 - 2022**

My research investigated a novel approach to methane mitigation in NZ’s dairy industry utilising in-paddock smart-feeders as a delivery mechanism for methane inhibitors. It contains two distinct elements, the adoption-diffusion of the approach throughout NZ’s dairy farming population and the approach’s economic performance in different scenarios. Both elements utilised modelling to quantitative modelling.

## Bachelor of Business (Economics, Finance)

**Massey University, 2018 - 2020**

-   International exchange to Purdue University to study agricultural economics driven by a desire to study behavioural economics, which was not offered domestically at the time
-   Tutored undergraduate courses (Economics for Business and Finance Fundamentals) of classes up sixty

# Skills

-   People
-   Presentation (farmers and academics)
-   Collaboration
-   Analytical and critical thinking
-   Best Practice Programming (R, GitHub, Data warehousing (Snowflake))

# Volunteer Experience

-   Organiser and chair of the R Community
-   NZARES Early Career Representative to the federal AARES council
-   NZARES Board Member
-   Health and Safety Officer -- University of Waikato Rugby Club

# Achievements

-   NZARES Post-graduate Conference Travel Award (NZARES, Nelson)
-   Flower Agribusiness Conference Travel Award (NZAE, Wellington)
-   DairyNZ Research Masters Scholarship
-   Fuji Xerox Global Exchange Scholarship
-   UHY Haines Norton Business Student Scholarship

# Interest

I love to get outdoors, be it playing, Ultimate Frisbee, Camping, Freediving, Mountain Biking or Fishing.
